from django.db import models

# Create your models here.

class User(models.Model):
    # Assuming 'id' is auto-generated by the database and is the primary key,
    # Django will handle it automatically unless you define a primary key field.
    # Since we created 'id' as AUTO_INCREMENT PRIMARY KEY, we don't need to define it here.

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    university_name = models.CharField(max_length=255, blank=True, null=True)
    semester_number = models.IntegerField(null=True, blank=True)
    gpa = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    nationality = models.CharField(max_length=100, blank=True, null=True)
    hobby = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
